# Generated by Django 3.1.4 on 2020-12-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runasystems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='children',
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='runasystems.categories'),
        ),
    ]
